-- Drop unique constraint and index on STATUS(NAME) if they exist
-- Names taken from error logs provided by user
ALTER TABLE STATUS DROP CONSTRAINT IF EXISTS UK_RECCGX9NR0A8DWV201T44L6PD;
DROP INDEX IF EXISTS UK_RECCGX9NR0A8DWV201T44L6PD_INDEX_E;
